# Site Settings
title: OoT Fan Site
email: taylorcgaines@gmail.com
description: >
  Ocarina of Time Pretend Site
baseurl: ""
url: "http://localhost:4000"
twitter_username: ZeldaIsABoy
github_username:  taylorcgaines
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
    characters:
        output: true
